# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 191, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.LoadImg = QtWidgets.QPushButton(self.groupBox_2)
        self.LoadImg.setGeometry(QtCore.QRect(20, 30, 151, 23))
        self.LoadImg.setObjectName("LoadImg")
        self.ShowTrainImages = QtWidgets.QPushButton(self.groupBox_2)
        self.ShowTrainImages.setGeometry(QtCore.QRect(20, 70, 151, 23))
        self.ShowTrainImages.setObjectName("ShowTrainImages")
        self.ShowModelStructure = QtWidgets.QPushButton(self.groupBox_2)
        self.ShowModelStructure.setGeometry(QtCore.QRect(20, 110, 151, 23))
        self.ShowModelStructure.setObjectName("ShowModelStructure")
        self.ShowDataAugmentation = QtWidgets.QPushButton(self.groupBox_2)
        self.ShowDataAugmentation.setGeometry(QtCore.QRect(20, 150, 151, 23))
        self.ShowDataAugmentation.setObjectName("ShowDataAugmentation")
        self.ShowAccuracyAndLoss = QtWidgets.QPushButton(self.groupBox_2)
        self.ShowAccuracyAndLoss.setGeometry(QtCore.QRect(20, 190, 151, 23))
        self.ShowAccuracyAndLoss.setObjectName("ShowAccuracyAndLoss")
        self.Inference = QtWidgets.QPushButton(self.groupBox_2)
        self.Inference.setGeometry(QtCore.QRect(20, 230, 151, 23))
        self.Inference.setObjectName("Inference")
        self.ShowText = QtWidgets.QLabel(self.centralwidget)
        self.ShowText.setGeometry(QtCore.QRect(250, 30, 171, 71))
        self.ShowText.setText("")
        self.ShowText.setObjectName("ShowText")
        self.ImgBox = QtWidgets.QLabel(self.centralwidget)
        self.ImgBox.setGeometry(QtCore.QRect(240, 110, 211, 191))
        self.ImgBox.setText("")
        self.ImgBox.setObjectName("ImgBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Resnet101 Test"))
        self.LoadImg.setText(_translate("MainWindow", "Load Image"))
        self.ShowTrainImages.setText(_translate("MainWindow", "1. Show Train Images"))
        self.ShowModelStructure.setText(_translate("MainWindow", "2. Show Model Structure"))
        self.ShowDataAugmentation.setText(_translate("MainWindow", "3. Show Data Augmentation "))
        self.ShowAccuracyAndLoss.setText(_translate("MainWindow", "4.Show Accuracy and Loss"))
        self.Inference.setText(_translate("MainWindow", "5.Inference"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
